apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: browser-extension-service-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi