apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-shared-pvc
  namespace: quilr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
  volumeName: efs-static-pv