apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  namespace: quilr
spec:
  selector:
    app: kafka-server
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-server
  namespace: quilr
spec:
  replicas: 1
  serviceName: kafka-server
  selector:
    matchLabels:
      app: kafka-server
  template:
    metadata:
      labels:
        app: kafka-server
    spec:
      hostname: kafka
      containers:
        - name: kafka
          image: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/tp/kafka:4.2.0
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-server:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "1"
            - name: KAFKA_LOG_RETENTION_MINUTES
              value: "60"
            - name: KAFKA_LOG_ROLL_MS
              value: "3600000"
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "10485760"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "10485760"
            - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
              value: "104857600"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
          volumeMounts:
            - name: kafka-server-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-server-data
          persistentVolumeClaim:
            claimName: kafka-server-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-server-pvc
  namespace: quilr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
