DROP TABLE IF EXISTS default.enriched_events ;

CREATE TABLE default.enriched_events
(
    `subscriberid` UUID,
    `tenantid` UUID,
    `alert_userprincipalname` LowCardinality(String),
    `alert_username` String,
    `app_name` LowCardinality(String),
    `domain` LowCardinality(String),
    `alert_appauthtype` LowCardinality(Nullable(String)) DEFAULT NULL,
    `alert_browsername` LowCardinality(Nullable(String)) DEFAULT NULL,
    `prompt_id` UUID,
    `alert_accountid` String,
    `alert_login_user` LowCardinality(String),
    `approval_status` LowCardinality(String),
    `app_owner` String,
    `app_type` String,
    `acc_app_type` String,
    `acc_status` String,
    `smart_groups` Array(String) DEFAULT [],
    `usr_groups` Array(String) DEFAULT [],
    `app_category` LowCardinality(String),
    `app_bus_category` LowCardinality(String),
    `app_sub_category` LowCardinality(String),
    `final_sensitive_l1_categories` Array(String),
    `final_sensitive_l2_categories` Array(String) DEFAULT [],
    `org_sensitive_l2_categories` Array(String) DEFAULT [],
    `event_time` UInt64,
    `alert_type` String,
    `alert_original_prompt` String,
    `alert_final_prompt` String,
    `alert_original_prompt_request_size` UInt64,
    `alert_user_justification` String,
    `alert_is_initial_sensitive` Bool,
    `alert_is_final_sensitive` Bool,
    `alert_prompt_changed` Bool,
    `control` String,
    `alert_action_taken` String,
    `alert_outcome` String,
    `alert_summary` String,
    `alert_action_name` String,
    `mode` String,
    `req_org_l2_attributes` String,
    `req_final_l2_attributes` String,
    `org_sensitive_l1_categories` Array(String),
    `prompt_category` LowCardinality(String),
    `alert_original_prompt_response` String,
    `alert_original_prompt_response_size` UInt64,
    `alert_final_prompt_response` String,
    `res_org_l2_attributes` String,
    `res_final_l2_attributes` String,
    `index_time` DateTime64(3, 'UTC') DEFAULT now64(3, 'UTC'),
    `start_of_week` DateTime MATERIALIZED toStartOfWeek(index_time),
    `user_status` String,
    `user_risk` String,
    `dept_current_score` Float64,
    `user_risk_num` Float64,
    `dept_prev_score` Float64,
    `user_prev_risk_num` Float64,
    `departments` String,
    `dept_risk` String,
    `ai_risk_beh_map` Map(String, UInt64),
    `org_response_l1_categories` Array(String),
    `org_response_l2_categories` String,
    INDEX approval_status_idx approval_status TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_alert_accountid alert_accountid TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX app_name_idx app_name TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX domain_idx domain TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/enriched_events', '{replica}')
PARTITION BY (subscriberid, tenantid, toYear(index_time), toMonth(index_time), toDayOfMonth(index_time))
ORDER BY (index_time, alert_userprincipalname, app_name, prompt_id)
TTL start_of_week + toIntervalYear(1)
SETTINGS index_granularity = 8192;
