CREATE TABLE IF NOT EXISTS default.quilr_asset_inventory
(
    `tenant_id` UUID,
    `subscriber_id` UUID,
    `subscription_id` UUID,
    `asset_platform_key` String,
    `asset_id` String,
    `provider` String,
    `platform` String,
    `asset_type` String,
    `asset_name` String,
    `asset_info` JSON,
    `asset_version` String,
    `asset_format` String,
    `subscription_info` JSON,
    `resource_group_id` String,
    `resource_group_info` JSON,
    `account_id` String,
    `account_info` JSON,
    `deployment_id` String,
    `deployment_name` String,
    `rai_policy_name` String,
    `system_data` JSON,
    `tags` Array(String),
    `risks` Array(String),
    `compliance` Array(String),
    `integration_points` Array(String),
    `endpoint` String,
    `status` String,
    `created_at` UInt64 DEFAULT toUInt64(now64()),
    `last_modified` UInt64 DEFAULT toUInt64(now64()),
    `index_time` DateTime64(3,
 'UTC') DEFAULT now64(3,
 'UTC'),
    `asset_job_name` String,
    `endpoint_name` String,
    `endpoint_info` JSON,
    `training_job_name` String,
    `training_job_tags` JSON,
    `training_job_info` JSON,
    `guardrails` Array(String),
    `agent_instructions` String,
    `rag_info` String,
    `rags` Array(String)
)
ENGINE = ReplacingMergeTree(last_modified)
PARTITION BY (subscriber_id,
 tenant_id)
ORDER BY (subscriber_id,
 tenant_id,
 asset_platform_key,
 platform,
 deployment_name)
SETTINGS index_granularity = 8192;