apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quilr-dlp-edm-pvc
  namespace: quilr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi 
  resources:
    requests:
      storage: 5Gi
