apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quilr-llm-gateway-pvc
  namespace: quilr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi  
  resources:
    requests:
      storage: 5Gi
